name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  create:
    branches: [master]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          user: "CoCreate-app"
          project: "CoCreate-dnd"
          repo: "CoCreate-app/CoCreate-dnd"
          token: ${{ secrets.GITHUB }}
          pullRequests: "true"
          prWoLabels: "true"
          issues: "true"
          issuesWoLabels: "true"
          author: "true"
          base: "HISTORY.md"
          unreleased: "true"
          breakingLabels: "Versioning - BREAKING"
          enhancementLabels: "Type - Enhancement, Type - Feature"
          bugLabels: "Type - Fix, Bug - Fixed"
          deprecatedLabels: "Type - Deprecated"
          removedLabels: "Type - Removal"
          securityLabels: "Security Fix"
          excludeLabels: "Skip-Changelog"

      - name: create commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "Automatic changelog update"
          file_pattern: "CHANGELOG.md"
