
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          user: "hssngl"
          project: "CoCreate-dnd"
          repo: "CoCreate/CoCreate-dnd"
          token: ${{ secrets.GITHUB }}
          pullRequests: "true"
          prWoLabels: "true"
          issues: "true"
          issuesWoLabels: "true"
          author: "true"
          base: "HISTORY.md"
          unreleased: "true"
          breakingLabels: "Versioning - BREAKING"
          enhancementLabels: "Type - Enhancement, Type - Feature"
          bugLabels: "Type - Fix, Bug - Fixed"
          deprecatedLabels: "Type - Deprecated"
          removedLabels: "Type - Removal"
          securityLabels: "Security Fix"
          excludeLabels: "Skip-Changelog"
       

