
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

